name: Release Boilerplate

on:
  push:
    branches:
      - main

env:
  PNPM_VERSION: ${{ vars.PNPM_VERSION }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  NEXT_PUBLIC_API_URL_BASE: ${{ vars.NEXT_PUBLIC_API_URL_BASE }}
  NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
  SITE_NAME: ${{ vars.SITE_NAME }}
  TWITTER_CREATOR: ${{ vars.TWITTER_CREATOR }}
  SITE_URL: ${{ vars.SITE_URL }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  RESEND_DOMAIN: ${{ vars.RESEND_DOMAIN }}
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_CURRENCY: ${{ vars.STRIPE_CURRENCY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  NEXT_PUBLIC_LANGUAGE: ${{ vars.NEXT_PUBLIC_LANGUAGE }}
  NEXT_PUBLIC_PERSONAL_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_PERSONAL_GITHUB_TOKEN }}

jobs:
  stats:
    name: Version Boilerplate
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🔥 Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${PNPM_VERSION} --activate

      - name: 📦 Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💣 build
        run: pnpm build

      - name: 💅 Prettier
        run: pnpm prettier

      # - name: 💎 lint:types
      #   run: pnpm turbo run lint:types --cache-dir=".turbo"

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: pnpm release
          commit: 'ci(release): Version X-boilerplate'
          title: 'ci(release): Version X-boilerplate - template'
